import type { Metadata } from "next";
import Link from "next/link";
import { BRAND_NAME, LIMITS, AI_HOST_FREE_BETA } from "@/lib/constants";
import { AVAILABLE_GAMES } from "@/lib/games";
import { Mascot } from "@/components/cartoon/Mascot";
import { TapedLabel } from "@/components/cartoon/Panel";
import { DoodleStar, SpotRays } from "@/components/cartoon/Doodles";
import { PublicFAQ } from "@/components/public/PublicFAQ";
import { Breadcrumbs } from "@/components/public/Breadcrumbs";

export const metadata: Metadata = {
  title: `Virtual Game Host for Party Games | ${BRAND_NAME}`,
  description:
    "Turn on the Virtual Host and play along with everyone else. It reads questions, announces results, reacts to the room, and keeps the game moving automatically.",
  openGraph: {
    title: `Virtual Game Host for Party Games | ${BRAND_NAME}`,
    description:
      "Turn on the Virtual Host and play along with everyone else. It reads questions, announces results, and keeps the game moving.",
  },
};

const INK = "#221f30";

const VH_FAQS = [
  {
    q: "Is the Virtual Host actually a real person?",
    a: "No. The Virtual Host is software. Some voice output and reactions are generated using artificial intelligence, including text-to-speech technology from ElevenLabs. It is not a live human performance.",
  },
  {
    q: "Can I still run the game manually instead?",
    a: "Yes. The Virtual Host is completely optional. Every game can be run in manual mode where you advance each round yourself.",
  },
  {
    q: "What does 'one Virtual Host game' count as?",
    a: "One game session with the Virtual Host on counts as one use against your monthly limit. The length of the session does not affect the count.",
  },
  {
    q: "What happens when I hit my monthly Virtual Host limit?",
    a: "You can still create and run rooms, you just switch to manual host mode for the rest of the month. Your limit resets at the start of each billing cycle.",
  },
  {
    q: "Are there different voices available?",
    a: "The Virtual Host uses a pre-selected voice. Additional voice options may be available on higher plans. The voice is generated by ElevenLabs using artificial intelligence.",
  },
  {
    q: "Does the Virtual Host hear or process player responses?",
    a: "No. The Virtual Host does not use microphones or audio input. It reads game state (what was submitted, who buzzed in, what the result was) and generates appropriate audio from that data.",
  },
  {
    q: "Is the Virtual Host free?",
    a: AI_HOST_FREE_BETA
      ? `Yes, during the current beta period, the Virtual Host is available on all plans including Free. The Free plan includes ${LIMITS.free.aiHostGamesPerMonth} Virtual Host game sessions per month.`
      : `The Virtual Host is available on all paid plans. The Free plan does not include Virtual Host access.`,
  },
];

export default function VirtualHostPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: VH_FAQS.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };

  return (
    <div className="relative overflow-hidden">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <SpotRays className="absolute left-0 top-0 h-full max-h-screen w-[55vw] opacity-50" />
      <SpotRays flip className="absolute right-0 top-0 h-full max-h-screen w-[55vw] opacity-30" />

      <div className="relative z-10 mx-auto w-full max-w-4xl px-6 pt-12">
        <Breadcrumbs
          items={[
            { label: BRAND_NAME, href: "/" },
            { label: "Virtual Host", href: "/virtual-host" },
          ]}
        />

        {/* Hero */}
        <div className="grid items-center gap-10 md:grid-cols-2">
          <div>
            <TapedLabel tilt={-1} color="var(--paper)">
              <span className="font-score text-[11px] uppercase tracking-[0.35em]" style={{ color: INK }}>
                optional · all 9 games
              </span>
            </TapedLabel>
            <h1
              className="font-display mt-3 text-4xl uppercase tracking-wide md:text-5xl"
              style={{ color: "var(--cream)" }}
            >
              Meet the {BRAND_NAME} Virtual Host
            </h1>
            <p className="font-hand mt-4 text-xl leading-snug" style={{ color: "var(--muted-foreground)" }}>
              Turn on the Virtual Host and play along with everyone else. It can read questions,
              explain rounds, announce results, keep the game moving, and react to what happens in
              the room.
            </p>
            <div className="mt-6 flex gap-3">
              <Link
                href="/signup"
                className="btn-rough px-6 py-3 text-xl"
                style={{ background: "var(--mustard)", color: INK }}
              >
                Try It Free
              </Link>
              <Link
                href="/games"
                className="font-score rounded-md border-2 border-current px-5 py-3 text-xs uppercase tracking-[0.2em]"
                style={{ color: "var(--cream)" }}
              >
                Choose a Game
              </Link>
            </div>
          </div>

          {/* Character panel */}
          <div className="flex justify-center">
            <div className="panel relative p-8" style={{ background: "var(--cream)" }}>
              <div className="flex flex-col items-center gap-4">
                <Mascot avatarId="wizard" size={110} expression="winner" animate={false} />
                <div className="panel-paper -rotate-1 px-4 py-2 text-center" style={{ background: "var(--paper)" }}>
                  <p className="font-hand text-xl" style={{ color: INK }}>
                    &ldquo;Interesting choice -<br />let&apos;s see what the room thinks!&rdquo;
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* What it does */}
        <section aria-labelledby="what-heading" className="mt-16">
          <h2
            id="what-heading"
            className="font-display mb-6 text-2xl uppercase tracking-wide"
            style={{ color: "var(--cream)" }}
          >
            What the Virtual Host Does
          </h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {[
              {
                headline: "Reads everything out loud",
                body: "Questions, prompts, player answers, and results are spoken aloud so everyone can follow along without staring at the big screen.",
              },
              {
                headline: "Reacts to what happens",
                body: "Correct answers get recognition. Close calls get a comment. A surprising result gets a reaction. The Virtual Host responds to game events, not a script.",
              },
              {
                headline: "Advances the game automatically",
                body: "No manual button presses between rounds. The Virtual Host manages timing and transitions so the host can play like everyone else.",
              },
              {
                headline: "Works on all 9 games",
                body: "Fact Frenzy, Two Truths & a Lie, Would You Rather, Most Likely To, Higher or Lower, Guess the Player, Shark Tank, Charades, and Number Rating.",
              },
            ].map(({ headline, body }) => (
              <div
                key={headline}
                className="panel-paper panel-grain flex flex-col gap-2 p-5"
                style={{ background: "var(--cream)" }}
              >
                <h3 className="font-display text-xl leading-tight" style={{ color: INK }}>
                  {headline}
                </h3>
                <p className="font-hand text-lg leading-snug" style={{ color: "#4a4460" }}>
                  {body}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Plan limits */}
        <section aria-labelledby="limits-heading" className="mt-14">
          <h2
            id="limits-heading"
            className="font-display mb-6 text-2xl uppercase tracking-wide"
            style={{ color: "var(--cream)" }}
          >
            Virtual Host on Each Plan
          </h2>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr>
                  <th
                    className="panel-paper p-4 text-left"
                    style={{ background: "var(--cream)", color: INK }}
                  >
                    <span className="font-display text-base">Plan</span>
                  </th>
                  <th
                    className="panel-paper p-4 text-left"
                    style={{ background: "var(--cream)", color: INK }}
                  >
                    <span className="font-display text-base">Virtual Host Games / Month</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {[
                  { plan: "Free", games: LIMITS.free.aiHostGamesPerMonth },
                  { plan: "Party Pass (24 h)", games: LIMITS.party_plus.aiHostGamesPerMonth },
                  { plan: "Party+", games: LIMITS.party_plus.aiHostGamesPerMonth },
                  { plan: "Pro Host", games: LIMITS.pro_host.aiHostGamesPerMonth },
                ].map(({ plan, games }) => (
                  <tr key={plan}>
                    <td className="panel-paper p-4" style={{ background: "var(--cream)" }}>
                      <span className="font-hand text-xl" style={{ color: "#4a4460" }}>{plan}</span>
                    </td>
                    <td className="panel-paper p-4" style={{ background: "var(--cream)" }}>
                      <span className="font-score text-2xl font-bold" style={{ color: INK }}>
                        {games}
                        {plan === "Free" && AI_HOST_FREE_BETA && (
                          <span className="font-hand ml-2 text-sm font-normal" style={{ color: "#8a7f63" }}>
                            (free during beta)
                          </span>
                        )}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="font-hand mt-3 text-lg" style={{ color: "var(--muted-foreground)" }}>
            Limits reset at the start of each billing cycle. Unused sessions do not roll over.
            When you reach your limit, the game continues in manual mode.
          </p>
        </section>

        {/* Technology note */}
        <section aria-labelledby="tech-heading" className="mt-14">
          <h2
            id="tech-heading"
            className="font-display mb-4 text-2xl uppercase tracking-wide"
            style={{ color: "var(--cream)" }}
          >
            About the Technology
          </h2>
          <div className="panel-paper panel-grain p-6" style={{ background: "var(--cream)" }}>
            <p className="font-hand text-xl leading-snug" style={{ color: "#4a4460" }}>
              The Virtual Host uses artificial intelligence to generate voice audio and context-aware
              reactions. Voice synthesis is powered by ElevenLabs. Game-state processing (reading
              answers, judging trivia responses) uses language model technology. The Virtual Host
              does not use microphones, does not record conversations, and does not process any
              audio input from the room.
            </p>
            <p className="font-hand mt-3 text-xl leading-snug" style={{ color: "#4a4460" }}>
              Player-submitted text (answers, statements, pitches) passes through AI processing for
              game mechanics like trivia judging and reaction generation. See our{" "}
              <Link href="/privacy" className="underline" style={{ color: INK }}>
                privacy policy
              </Link>{" "}
              for details on how this data is handled.
            </p>
          </div>
        </section>

        {/* Games list */}
        <section aria-labelledby="games-heading" className="mt-14">
          <h2
            id="games-heading"
            className="font-display mb-4 text-2xl uppercase tracking-wide"
            style={{ color: "var(--cream)" }}
          >
            Virtual Host, Supported Games
          </h2>
          <div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">
            {AVAILABLE_GAMES.map((game) => (
              <Link
                key={game.slug}
                href={`/games/${game.slug}`}
                className="panel-paper panel-grain flex items-center gap-3 p-3 transition-opacity hover:opacity-80"
                style={{ background: "var(--cream)" }}
              >
                <span
                  className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border-2"
                  style={{ background: game.color, borderColor: INK }}
                  aria-hidden
                />
                <div>
                  <span className="font-display text-base leading-tight" style={{ color: INK }}>
                    {game.name}
                  </span>
                  <span className="font-score ml-2 text-[9px] uppercase tracking-widest" style={{ color: "var(--teal)" }}>
                    ✓ supported
                  </span>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section aria-labelledby="faq-heading" className="mt-14">
          <h2
            id="faq-heading"
            className="font-display mb-6 text-2xl uppercase tracking-wide"
            style={{ color: "var(--cream)" }}
          >
            Virtual Host Questions
          </h2>
          <PublicFAQ items={VH_FAQS} withSchema={false} />
        </section>

        {/* CTA */}
        <div className="mb-20 mt-12 text-center">
          <div className="panel-paper panel-grain inline-flex flex-col items-center gap-4 px-10 py-8" style={{ background: "var(--cream)" }}>
            <DoodleStar size={30} />
            <h2 className="font-display text-2xl uppercase" style={{ color: INK }}>
              Try the Virtual Host free
            </h2>
            <p className="font-hand text-xl" style={{ color: "#4a4460" }}>
              {AI_HOST_FREE_BETA
                ? `Included on all plans during beta. ${LIMITS.free.aiHostGamesPerMonth} game sessions per month on the free plan.`
                : "Available on paid plans."}
            </p>
            <Link
              href="/signup"
              className="btn-rough px-8 py-3 text-xl"
              style={{ background: "var(--mustard)", color: INK }}
            >
              Host a Game Free
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
