import type { Metadata } from "next";
import Link from "next/link";
import { BRAND_NAME } from "@/lib/constants";
import { Breadcrumbs } from "@/components/public/Breadcrumbs";
import { TapedLabel } from "@/components/cartoon/Panel";

export const metadata: Metadata = {
  title: `Privacy Policy | ${BRAND_NAME}`,
  description: `How ScreenParty collects, uses, and protects your data.`,
};

const INK = "#221f30";

export default function PrivacyPage() {
  return (
    <div className="relative z-10 mx-auto w-full max-w-3xl px-6 pt-12 pb-20">
      <Breadcrumbs
        items={[
          { label: BRAND_NAME, href: "/" },
          { label: "Privacy Policy", href: "/privacy" },
        ]}
      />

      <TapedLabel tilt={-1} color="var(--paper)">
        <span className="font-score text-[11px] uppercase tracking-[0.35em]" style={{ color: INK }}>
          legal
        </span>
      </TapedLabel>
      <h1
        className="font-display mt-3 text-4xl uppercase tracking-wide"
        style={{ color: "var(--cream)" }}
      >
        Privacy Policy
      </h1>
      <p className="font-hand mt-2 text-lg" style={{ color: "var(--muted-foreground)" }}>
        Last updated: July 2026
      </p>

      <div className="prose-custom mt-8 flex flex-col gap-6">
        <LegalSection title="Overview">
          <p>
            ScreenParty (&ldquo;we,&rdquo; &ldquo;our,&rdquo; &ldquo;us&rdquo;) operates the
            ScreenParty platform at screenparty.gg. This policy explains what data we collect, how
            we use it, and your choices.
          </p>
          <p>
            Players who join a room using a room code do not create accounts. Hosts create accounts
            to create and manage rooms.
          </p>
        </LegalSection>

        <LegalSection title="Data We Collect">
          <h3 className="font-display text-lg" style={{ color: INK }}>Host accounts</h3>
          <ul>
            <li>Email address (required for sign-up)</li>
            <li>Password (stored as a secure hash, never in plain text)</li>
            <li>Billing information (handled by Stripe, we do not store card numbers)</li>
            <li>Usage data: rooms created, games played, Virtual Host sessions used</li>
          </ul>

          <h3 className="font-display mt-4 text-lg" style={{ color: INK }}>Players (anonymous)</h3>
          <ul>
            <li>Display name chosen at join time</li>
            <li>Avatar selection</li>
            <li>Game responses submitted during play (answers, votes, pitches)</li>
            <li>A temporary session token stored in localStorage, expires with the room</li>
          </ul>

          <h3 className="font-display mt-4 text-lg" style={{ color: INK }}>Automatically collected</h3>
          <ul>
            <li>Basic page-view analytics via Vercel Analytics (no cookies, privacy-safe)</li>
            <li>IP address and browser type for security and abuse prevention</li>
          </ul>
        </LegalSection>

        <LegalSection title="Virtual Host and AI Processing">
          <p>
            When the Virtual Host is enabled, player-submitted text (answers, statements, guesses,
            pitches) may be sent to third-party AI providers for game mechanics such as answer
            judging and reaction generation. Voice output is generated by ElevenLabs.
          </p>
          <p>
            The Virtual Host does not use microphones and does not record or process any audio from
            the room. Player data sent to AI providers is used only for the active game session and
            is not used to train AI models on our behalf.
          </p>
        </LegalSection>

        <LegalSection title="How We Use Your Data">
          <ul>
            <li>To provide and operate the ScreenParty platform</li>
            <li>To process billing and subscriptions through Stripe</li>
            <li>To enforce plan limits and track usage</li>
            <li>To improve the product through aggregated, anonymised analytics</li>
            <li>To communicate account and billing information to hosts</li>
          </ul>
          <p>We do not sell personal data. We do not use personal data for advertising.</p>
        </LegalSection>

        <LegalSection title="Data Retention">
          <p>
            Host account data is retained while the account is active. You may request deletion of
            your account and associated data at any time from your account page or by contacting us.
          </p>
          <p>
            Player session tokens and game responses are ephemeral and expire when the room session
            ends. We do not permanently associate anonymous player responses with identifiable individuals.
          </p>
        </LegalSection>

        <LegalSection title="Third-Party Services">
          <ul>
            <li>
              <strong>Supabase</strong>, database and authentication provider. Your data is stored
              in Supabase-managed infrastructure.
            </li>
            <li>
              <strong>Stripe</strong>, payment processing. Stripe&apos;s privacy policy governs
              billing data.
            </li>
            <li>
              <strong>OpenAI</strong>, used for trivia answer judging and Virtual Host reactions
              when enabled.
            </li>
            <li>
              <strong>ElevenLabs</strong>, used for Virtual Host voice synthesis when enabled.
            </li>
            <li>
              <strong>Vercel</strong>, hosting and analytics. Vercel Analytics is privacy-safe and
              does not use cookies.
            </li>
          </ul>
        </LegalSection>

        <LegalSection title="Cookies">
          <p>
            ScreenParty uses minimal cookies. Authentication sessions use secure HTTP-only cookies
            managed by Supabase. We do not use advertising cookies or third-party tracking cookies.
          </p>
        </LegalSection>

        <LegalSection title="Your Rights">
          <p>
            You may request access to, correction of, or deletion of your personal data. Contact us
            through your account dashboard. We will respond within 30 days.
          </p>
        </LegalSection>

        <LegalSection title="Contact">
          <p>
            {/* Owner decision needed: replace with actual contact email */}
            For privacy questions, contact us through your account dashboard or at the email
            address associated with your host account.
          </p>
        </LegalSection>
      </div>

      <div className="mt-8">
        <Link href="/terms" className="font-score text-[10px] uppercase tracking-[0.25em] underline" style={{ color: "var(--cream)" }}>
          Terms of Service →
        </Link>
      </div>
    </div>
  );
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  const INK = "#221f30";
  return (
    <div className="panel-paper panel-grain p-6" style={{ background: "var(--cream)" }}>
      <h2 className="font-display mb-3 text-xl uppercase tracking-wide" style={{ color: INK }}>
        {title}
      </h2>
      <div
        className="font-hand flex flex-col gap-2 text-lg leading-snug [&_li]:ml-4 [&_li]:list-disc [&_strong]:font-display [&_p]:leading-snug"
        style={{ color: "#4a4460" }}
      >
        {children}
      </div>
    </div>
  );
}
